version: 0.0.{build}
image: Visual Studio 2017
configuration:
- Debug
platform: Any CPU
before_build:
- cmd: nuget restore -verbosity quiet
build_script:
- cmd: msbuild UtaFormatEx.sln /p:Configuration=Release /verbosity:quiet
artifacts:
- path: UtaFormat\bin\Release
  name: UtaFormatEx
  type: exe
